version: "3.4"

services:
  app:
    container_name: redirect_app
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: ${IMAGE_APP}
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: always
    logging:
      driver: journald
    env_file:
      - .env
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  nginx:
    container_name: redirect_nginx
    build: ./nginx
    image: ${IMAGE_NGINX}
    restart: always
    ports:
      - 127.0.0.1:${PORT}:80
    depends_on:
      - app
    volumes:
      - nginx_log_volume:/var/log/nginx
    logging:
      driver: journald


volumes:
  nginx_log_volume:
