[tool.poetry]
name = "redirect"
version = "0.1.0"
description = "Redirect service"
authors = ["DipCoy <dipolarcoyote@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.87.0"
uvicorn = "^0.19.0"
